defaults:
  - scope:
      path: ""
    values:
      layout: "default"

timezone: "Europe/Amsterdam"
dob: "2022"
company: "Init Power B.V."
coc-number: "87391597"
address:  ""
deployurl: "https://init-power.com/"
welcome: "Init Power"
welcome-alt: "Bezoek Init Power"
linkedinurl:  "https://www.linkedin.com/company/init-power"
email: "info@init-power.com"
label: "IP"
